name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --deny notes --sizes 
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Check Gas Snapshots are up to date
        run: |
          if ! git diff --exit-code snapshots/; then
            echo "::error::Gas snapshots are out of date. Please run 'forge t' locally and commit the updated snapshot files."
            exit 1
          fi
